package com.keyscan.desktop

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.keyscan.core.model.AppLanguage

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

private val keys = listOf("setup_title", "setup_intro", "setup_heading", "custody", "pin_new", "pin_again", "key_new", "key_again", "mismatch", "create", "unlock_title", "unlock_intro", "bad_credentials", "unlock", "reauth_title", "reauth_intro", "verify", "cancel")
private val messages: Map<AppLanguage, List<String>> = mapOf(
    AppLanguage.ENGLISH to listOf("Create your local secure vault", "No account required. Use exactly the same PIN and data encryption key on every platform, or secure backups cannot be decrypted.", "Initial security setup", "You are responsible for safeguarding the PIN and data encryption key. KeyScan cannot recover them.", "Set PIN (at least 6 digits)", "Enter PIN again", "Data encryption key (at least 12 characters)", "Enter data encryption key again", "Both entries must match exactly, including capitalization and spaces.", "Create secure vault", "Unlock secure vault", "Enter the PIN and data encryption key used when this vault was created.", "The PIN or data encryption key is incorrect.", "Unlock", "Enable edit mode", "Verify again before editing sensitive data.", "Verify", "Cancel"),
    AppLanguage.SIMPLIFIED_CHINESE to listOf("创建你的本地安全保险箱", "无需账号。请确保所有平台使用完全相同的 PIN 和数据加密密钥，否则无法解密安全备份。", "首次安全设置", "PIN 与数据加密密钥均由你保管，KeyScan 无法替你找回。", "设置 PIN（至少6位）", "再次输入 PIN", "数据加密密钥（至少12字符）", "再次输入数据加密密钥", "两次输入必须完全一致，包括大小写和空格。", "创建安全保险箱", "解锁安全保险箱", "请输入创建保险箱时使用的 PIN 和数据加密密钥。", "PIN 或数据加密密钥不正确。", "解锁", "启用编辑模式", "编辑敏感数据前需要再次验证。", "验证", "取消"),
    AppLanguage.TRADITIONAL_CHINESE to listOf("建立你的本機安全保險箱", "無需帳號。請確保所有平台使用完全相同的 PIN 與資料加密金鑰，否則無法解密安全備份。", "首次安全設定", "PIN 與資料加密金鑰均由你保管，KeyScan 無法替你找回。", "設定 PIN（至少 6 位數）", "再次輸入 PIN", "資料加密金鑰（至少 12 個字元）", "再次輸入資料加密金鑰", "兩次輸入必須完全一致，包括大小寫與空格。", "建立安全保險箱", "解鎖安全保險箱", "請輸入建立保險箱時使用的 PIN 與資料加密金鑰。", "PIN 或資料加密金鑰不正確。", "解鎖", "啟用編輯模式", "編輯敏感資料前需要再次驗證。", "驗證", "取消"),
    AppLanguage.JAPANESE to listOf("ローカル保管庫を作成", "アカウントは不要です。すべての端末で同じ PIN とデータ暗号化キーを使用してください。異なる場合、バックアップを復号できません。", "初回セキュリティ設定", "PIN とデータ暗号化キーはご自身で保管してください。KeyScan では復元できません。", "PIN を設定（6桁以上）", "PIN を再入力", "データ暗号化キー（12文字以上）", "データ暗号化キーを再入力", "大文字、小文字、空白を含め、入力内容が完全に一致する必要があります。", "保管庫を作成", "保管庫をロック解除", "保管庫の作成時に使用した PIN とデータ暗号化キーを入力してください。", "PIN またはデータ暗号化キーが正しくありません。", "ロック解除", "編集モードを有効化", "機密データを編集する前に再認証してください。", "認証", "キャンセル"),
    AppLanguage.KOREAN to listOf("로컬 보안 금고 만들기", "계정이 필요하지 않습니다. 모든 플랫폼에서 동일한 PIN과 데이터 암호화 키를 사용해야 백업을 복호화할 수 있습니다.", "최초 보안 설정", "PIN과 데이터 암호화 키는 사용자가 보관해야 하며 KeyScan은 복구할 수 없습니다.", "PIN 설정(6자리 이상)", "PIN 다시 입력", "데이터 암호화 키(12자 이상)", "데이터 암호화 키 다시 입력", "대소문자와 공백을 포함해 두 입력이 완전히 일치해야 합니다.", "보안 금고 만들기", "보안 금고 잠금 해제", "금고를 만들 때 사용한 PIN과 데이터 암호화 키를 입력하세요.", "PIN 또는 데이터 암호화 키가 올바르지 않습니다.", "잠금 해제", "편집 모드 사용", "민감한 데이터를 편집하기 전에 다시 인증하세요.", "인증", "취소"),
    AppLanguage.GERMAN to listOf("Lokalen sicheren Tresor erstellen", "Kein Konto erforderlich. Verwenden Sie auf allen Plattformen exakt dieselbe PIN und denselben Datenverschlüsselungsschlüssel.", "Erste Sicherheitseinrichtung", "PIN und Datenverschlüsselungsschlüssel liegen in Ihrer Verantwortung. KeyScan kann sie nicht wiederherstellen.", "PIN festlegen (mindestens 6 Stellen)", "PIN erneut eingeben", "Datenverschlüsselungsschlüssel (mindestens 12 Zeichen)", "Schlüssel erneut eingeben", "Beide Eingaben müssen einschließlich Groß-/Kleinschreibung und Leerzeichen übereinstimmen.", "Sicheren Tresor erstellen", "Tresor entsperren", "Geben Sie PIN und Datenverschlüsselungsschlüssel dieses Tresors ein.", "PIN oder Datenverschlüsselungsschlüssel ist falsch.", "Entsperren", "Bearbeitungsmodus aktivieren", "Vor dem Bearbeiten sensibler Daten erneut bestätigen.", "Bestätigen", "Abbrechen"),
    AppLanguage.SPANISH to listOf("Crear bóveda segura local", "No se requiere una cuenta. Usa exactamente el mismo PIN y la misma clave de cifrado de datos en todas las plataformas.", "Configuración de seguridad inicial", "Tú custodias el PIN y la clave de cifrado. KeyScan no puede recuperarlos.", "Configurar PIN (mínimo 6 dígitos)", "Repetir PIN", "Clave de cifrado (mínimo 12 caracteres)", "Repetir clave de cifrado", "Ambas entradas deben coincidir exactamente, incluidas mayúsculas y espacios.", "Crear bóveda segura", "Desbloquear bóveda", "Introduce el PIN y la clave usados al crear la bóveda.", "El PIN o la clave de cifrado no son correctos.", "Desbloquear", "Activar modo de edición", "Vuelve a verificarte antes de editar datos sensibles.", "Verificar", "Cancelar"),
    AppLanguage.FRENCH to listOf("Créer votre coffre local sécurisé", "Aucun compte requis. Utilisez exactement le même code PIN et la même clé de chiffrement sur toutes les plateformes.", "Configuration initiale de sécurité", "Vous devez conserver le code PIN et la clé de chiffrement. KeyScan ne peut pas les récupérer.", "Définir le code PIN (6 chiffres minimum)", "Saisir à nouveau le code PIN", "Clé de chiffrement (12 caractères minimum)", "Saisir à nouveau la clé", "Les deux saisies doivent être identiques, y compris la casse et les espaces.", "Créer le coffre sécurisé", "Déverrouiller le coffre", "Saisissez le code PIN et la clé utilisés lors de la création du coffre.", "Le code PIN ou la clé de chiffrement est incorrect.", "Déverrouiller", "Activer le mode édition", "Vérifiez à nouveau votre identité avant de modifier des données sensibles.", "Vérifier", "Annuler"),
    AppLanguage.ITALIAN to listOf("Crea la cassaforte locale", "Non serve un account. Usa esattamente lo stesso PIN e la stessa chiave di crittografia su tutte le piattaforme.", "Configurazione di sicurezza iniziale", "PIN e chiave di crittografia sono sotto la tua responsabilità. KeyScan non può recuperarli.", "Imposta PIN (almeno 6 cifre)", "Inserisci di nuovo il PIN", "Chiave di crittografia (almeno 12 caratteri)", "Inserisci di nuovo la chiave", "Le due immissioni devono coincidere esattamente, inclusi maiuscole e spazi.", "Crea cassaforte", "Sblocca cassaforte", "Inserisci PIN e chiave usati per creare la cassaforte.", "Il PIN o la chiave non sono corretti.", "Sblocca", "Attiva modalità modifica", "Verifica di nuovo prima di modificare dati sensibili.", "Verifica", "Annulla"),
    AppLanguage.DUTCH to listOf("Lokale veilige kluis maken", "Geen account nodig. Gebruik op elk platform exact dezelfde pincode en gegevensversleutelingssleutel.", "Eerste beveiligingsinstelling", "U beheert zelf de pincode en versleutelingssleutel. KeyScan kan ze niet herstellen.", "Pincode instellen (minstens 6 cijfers)", "Pincode opnieuw invoeren", "Versleutelingssleutel (minstens 12 tekens)", "Sleutel opnieuw invoeren", "Beide invoeren moeten exact gelijk zijn, inclusief hoofdletters en spaties.", "Veilige kluis maken", "Kluis ontgrendelen", "Voer de pincode en sleutel in waarmee deze kluis is gemaakt.", "De pincode of versleutelingssleutel is onjuist.", "Ontgrendelen", "Bewerkmodus inschakelen", "Verifieer opnieuw voordat u gevoelige gegevens bewerkt.", "Verifiëren", "Annuleren"),
    AppLanguage.PORTUGUESE_BRAZIL to listOf("Criar cofre seguro local", "Não é preciso ter conta. Use exatamente o mesmo PIN e a mesma chave de criptografia em todas as plataformas.", "Configuração inicial de segurança", "Você é responsável pelo PIN e pela chave de criptografia. O KeyScan não pode recuperá-los.", "Definir PIN (pelo menos 6 dígitos)", "Digite o PIN novamente", "Chave de criptografia (pelo menos 12 caracteres)", "Digite a chave novamente", "As duas entradas devem ser idênticas, inclusive maiúsculas e espaços.", "Criar cofre seguro", "Desbloquear cofre", "Digite o PIN e a chave usados na criação do cofre.", "O PIN ou a chave de criptografia está incorreto.", "Desbloquear", "Ativar modo de edição", "Verifique novamente antes de editar dados confidenciais.", "Verificar", "Cancelar"),
    AppLanguage.RUSSIAN to listOf("Создать локальное защищённое хранилище", "Учётная запись не нужна. Используйте одинаковые PIN-код и ключ шифрования данных на всех платформах.", "Первоначальная настройка безопасности", "Вы отвечаете за хранение PIN-кода и ключа шифрования. KeyScan не может их восстановить.", "Задайте PIN-код (не менее 6 цифр)", "Введите PIN-код ещё раз", "Ключ шифрования (не менее 12 символов)", "Введите ключ ещё раз", "Оба значения должны полностью совпадать, включая регистр и пробелы.", "Создать защищённое хранилище", "Разблокировать хранилище", "Введите PIN-код и ключ, использованные при создании хранилища.", "Неверный PIN-код или ключ шифрования.", "Разблокировать", "Включить режим редактирования", "Перед изменением конфиденциальных данных пройдите проверку ещё раз.", "Проверить", "Отмена")
)

// These two inputs are constrained by the shared Android-compatible core, not
// by the older prose that originally accompanied the desktop prototype.
private val currentSecurityInputLabels = mapOf(
    AppLanguage.ENGLISH to listOf("Set PIN (4–6 digits)", "Data encryption key (8–32 characters)"),
    AppLanguage.SIMPLIFIED_CHINESE to listOf("设置 PIN（4–6 位）", "数据加密密钥（8–32 个字符）"),
    AppLanguage.TRADITIONAL_CHINESE to listOf("設定 PIN（4–6 位數）", "資料加密金鑰（8–32 個字元）"),
    AppLanguage.JAPANESE to listOf("PIN を設定（4～6桁）", "データ暗号化キー（8～32文字）"),
    AppLanguage.KOREAN to listOf("PIN 설정(4~6자리)", "데이터 암호화 키(8~32자)"),
    AppLanguage.GERMAN to listOf("PIN festlegen (4–6 Stellen)", "Datenverschlüsselungsschlüssel (8–32 Zeichen)"),
    AppLanguage.SPANISH to listOf("Configurar PIN (4–6 dígitos)", "Clave de cifrado de datos (8–32 caracteres)"),
    AppLanguage.FRENCH to listOf("Définir le code PIN (4 à 6 chiffres)", "Clé de chiffrement des données (8 à 32 caractères)"),
    AppLanguage.ITALIAN to listOf("Imposta PIN (4–6 cifre)", "Chiave di crittografia dei dati (8–32 caratteri)"),
    AppLanguage.DUTCH to listOf("Pincode instellen (4–6 cijfers)", "Gegevensversleutelingssleutel (8–32 tekens)"),
    AppLanguage.PORTUGUESE_BRAZIL to listOf("Definir PIN (4–6 dígitos)", "Chave de criptografia de dados (8–32 caracteres)"),
    AppLanguage.RUSSIAN to listOf("Задайте PIN-код (4–6 цифр)", "Ключ шифрования данных (8–32 символа)")
)

fun message(language: AppLanguage, key: String): String {
    val resolved = resolvedLanguage(language)
    if (key == "pin_new") return currentSecurityInputLabels.getValue(resolved)[0]
    if (key == "key_new") return currentSecurityInputLabels.getValue(resolved)[1]
    val index = keys.indexOf(key); require(index >= 0) { "Unknown message key: $key" }
    return checkNotNull(messages[resolved] ?: messages[AppLanguage.ENGLISH]).getOrElse(index) { messages.getValue(AppLanguage.ENGLISH)[index] }
}

@Composable fun m(key: String): String = message(LocalAppLanguage.current, key)
fun messageKeys(): List<String> = keys
