package com.keyscan.desktop

import androidx.compose.runtime.Composable
import com.keyscan.core.model.AppLanguage

private val vaultKeys = listOf("count", "add", "search", "empty", "details", "edit", "delete", "title", "category", "fields", "notes", "save", "attachments", "add_attachment", "no_attachment", "verify_export", "close", "choose_attachment", "export_attachment")
private val vaultMessages = mapOf(
    AppLanguage.ENGLISH to listOf("%d secure items", "Add item", "Search title or category", "No secure-vault items yet", "Details & attachments", "Edit", "Delete", "Title", "Category", "Secure fields (JSON)", "Notes", "Save", "Encrypted attachments (%d)", "Add attachment", "No attachments yet", "Verify & export", "Close", "Choose a file to encrypt", "Export decrypted attachment"),
    AppLanguage.SIMPLIFIED_CHINESE to listOf("%d 个安全项目", "添加项目", "搜索标题或分类", "还没有安全保险箱项目", "详情与附件", "编辑", "删除", "标题", "分类", "安全字段（JSON）", "备注", "保存", "加密附件（%d）", "添加附件", "还没有附件", "验证并导出", "关闭", "选择要加密保存的附件", "导出解密后的附件"),
    AppLanguage.TRADITIONAL_CHINESE to listOf("%d 個安全項目", "新增項目", "搜尋標題或分類", "尚無安全保險箱項目", "詳細資料與附件", "編輯", "刪除", "標題", "分類", "安全欄位（JSON）", "備註", "儲存", "加密附件（%d）", "新增附件", "尚無附件", "驗證並匯出", "關閉", "選擇要加密儲存的附件", "匯出解密後的附件"),
    AppLanguage.JAPANESE to listOf("安全項目 %d 件", "項目を追加", "タイトルまたはカテゴリを検索", "安全保管庫に項目はありません", "詳細と添付ファイル", "編集", "削除", "タイトル", "カテゴリ", "安全フィールド（JSON）", "メモ", "保存", "暗号化された添付ファイル（%d）", "添付ファイルを追加", "添付ファイルはありません", "認証してエクスポート", "閉じる", "暗号化して保存するファイルを選択", "復号した添付ファイルをエクスポート"),
    AppLanguage.KOREAN to listOf("보안 항목 %d개", "항목 추가", "제목 또는 분류 검색", "보안 금고 항목이 없습니다", "세부 정보 및 첨부 파일", "편집", "삭제", "제목", "분류", "보안 필드(JSON)", "메모", "저장", "암호화된 첨부 파일(%d)", "첨부 파일 추가", "첨부 파일이 없습니다", "인증 후 내보내기", "닫기", "암호화해 저장할 파일 선택", "복호화된 첨부 파일 내보내기"),
    AppLanguage.GERMAN to listOf("%d sichere Einträge", "Eintrag hinzufügen", "Titel oder Kategorie suchen", "Noch keine Tresoreinträge", "Details und Anhänge", "Bearbeiten", "Löschen", "Titel", "Kategorie", "Sichere Felder (JSON)", "Notizen", "Speichern", "Verschlüsselte Anhänge (%d)", "Anhang hinzufügen", "Keine Anhänge", "Prüfen und exportieren", "Schließen", "Zu verschlüsselnde Datei auswählen", "Entschlüsselten Anhang exportieren"),
    AppLanguage.SPANISH to listOf("%d elementos seguros", "Añadir elemento", "Buscar título o categoría", "Aún no hay elementos seguros", "Detalles y adjuntos", "Editar", "Eliminar", "Título", "Categoría", "Campos seguros (JSON)", "Notas", "Guardar", "Adjuntos cifrados (%d)", "Añadir adjunto", "No hay adjuntos", "Verificar y exportar", "Cerrar", "Elegir archivo para cifrar", "Exportar adjunto descifrado"),
    AppLanguage.FRENCH to listOf("%d éléments sécurisés", "Ajouter un élément", "Rechercher un titre ou une catégorie", "Aucun élément sécurisé", "Détails et pièces jointes", "Modifier", "Supprimer", "Titre", "Catégorie", "Champs sécurisés (JSON)", "Notes", "Enregistrer", "Pièces jointes chiffrées (%d)", "Ajouter une pièce jointe", "Aucune pièce jointe", "Vérifier et exporter", "Fermer", "Choisir le fichier à chiffrer", "Exporter la pièce jointe déchiffrée"),
    AppLanguage.ITALIAN to listOf("%d elementi sicuri", "Aggiungi elemento", "Cerca titolo o categoria", "Nessun elemento sicuro", "Dettagli e allegati", "Modifica", "Elimina", "Titolo", "Categoria", "Campi protetti (JSON)", "Note", "Salva", "Allegati crittografati (%d)", "Aggiungi allegato", "Nessun allegato", "Verifica ed esporta", "Chiudi", "Scegli file da crittografare", "Esporta allegato decrittografato"),
    AppLanguage.DUTCH to listOf("%d veilige items", "Item toevoegen", "Zoek op titel of categorie", "Nog geen kluisitems", "Details en bijlagen", "Bewerken", "Verwijderen", "Titel", "Categorie", "Beveiligde velden (JSON)", "Notities", "Opslaan", "Versleutelde bijlagen (%d)", "Bijlage toevoegen", "Geen bijlagen", "Verifiëren en exporteren", "Sluiten", "Te versleutelen bestand kiezen", "Ontsleutelde bijlage exporteren"),
    AppLanguage.PORTUGUESE_BRAZIL to listOf("%d itens seguros", "Adicionar item", "Pesquisar título ou categoria", "Ainda não há itens seguros", "Detalhes e anexos", "Editar", "Excluir", "Título", "Categoria", "Campos seguros (JSON)", "Notas", "Salvar", "Anexos criptografados (%d)", "Adicionar anexo", "Nenhum anexo", "Verificar e exportar", "Fechar", "Escolher arquivo para criptografar", "Exportar anexo descriptografado"),
    AppLanguage.RUSSIAN to listOf("Защищённых элементов: %d", "Добавить элемент", "Поиск по названию или категории", "В хранилище пока нет элементов", "Сведения и вложения", "Изменить", "Удалить", "Название", "Категория", "Защищённые поля (JSON)", "Заметки", "Сохранить", "Зашифрованные вложения: %d", "Добавить вложение", "Вложений нет", "Проверить и экспортировать", "Закрыть", "Выберите файл для шифрования", "Экспорт расшифрованного вложения")
)

fun vaultMessage(language: AppLanguage, key: String, vararg args: Any): String { val index = vaultKeys.indexOf(key); require(index >= 0); val template = (vaultMessages[resolvedLanguage(language)] ?: vaultMessages.getValue(AppLanguage.ENGLISH))[index]; return if (args.isEmpty()) template else template.format(*args) }
@Composable fun vm(key: String, vararg args: Any): String = vaultMessage(LocalAppLanguage.current, key, *args)
fun vaultMessageKeys() = vaultKeys
